version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/node:lts-buster
    steps:
      - checkout
      - run: npm install
      - run: npm run lerna -- bootstrap
      - run: npm run lerna run build
  lint:
    docker:
      - image: circleci/node:lts-buster
    steps:
      - checkout
      - run: npm install
      - run: npm run lerna bootstrap
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:lts-buster
    steps:
      - checkout
      - run: npm install
      - run: npm run lerna bootstrap
      - run: npm run test -- --runInBand
      - codecov/upload:
          file: .coverage/*.json
  integration-tests:
    docker:
      - image: circleci/node:lts-buster
    steps:
      - checkout
      - run: npm install
      - run: npm run lerna bootstrap
      - run: npm run build
      - run: cd integration-tests && npm run test
  deploy-docs:
    docker:
      - image: circleci/node:10-buster
    steps:
      - checkout
      - run: npm install
      - run: npm run lerna -- bootstrap
      - run: npm run lerna run build
      - run: cd website && cp -R build/. ../dist
      - run: npm run build-docs
      - run: cd packages/taquito-react-components && npm run build-storybook -- -o ../../dist/react-storybook
      - run: cd dist && touch .nojekyll && echo 'tezostaquito.io' > CNAME
      - run:
          command: |
            git config user.email "ci-build@ecadlabs.com"
            git config user.name "ci-build"
            npm run gh-pages -- --dist dist --dotfiles --silent --repo https://$GITHUB_TOKEN@github.com/ecadlabs/taquito.git
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - lint
      - test
      - deploy-docs:
          filters:
            branches:
              only: master
  integration:
    jobs:
      - approve-tests:
          type: approval
          filters:
            branches:
              only: master
      - integration-tests:
          requires:
            - approve-tests
          filters:
            branches:
              only: master

