name: Algolia indexing

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  delete-current-algolia-index:
    env:
      ALGOLIA_UPDATE_API_KEY: ${{secrets.ALGOLIA_UPDATE_API_KEY}}
      ALGOLIA_SEARCH_API_KEY: ${{secrets.ALGOLIA_SEARCH_API_KEY}}
      ALGOLIA_APPLICATION_ID: ${{secrets.ALGOLIA_APPLICATION_ID}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - name: Run delete script
      run: npm -w @taquito/website run delete-index
    - name: Algolia Indexing
      run: |
        docker run --rm -e "CONFIG=$(cat ./website/config.json | jq -r tostring)" \
          -e API_KEY=${{secrets.ALGOLIA_UPDATE_API_KEY}} \
          -e APPLICATION_ID=${{secrets.ALGOLIA_APPLICATION_ID}} \
          algolia/docsearch-scraper

    - name: Slack Notification
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        token: ${{ secrets.GITHUB_TOKEN }}
        notification_title: "Taquito Algolia Indexing ${{job.status}}"
        message_format: "{emoji} *{workflow}* {status_message} on <{commit_url}|{commit_sha}> | <{run_url}|View Run>"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.ALGOLIA_SLACK_WEBHOOK }}
      
      













