name: Deploy Edge

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  deploy-edge-package:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/master' }}
    strategy:
      matrix:
        node: [12.x]
    env:
      VERDACCIO_TOKEN: ${{ secrets.EDGE_VERDACCIO_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodet }}
    - run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - run: echo "PACKAGE_VERSION=`node -p "require('./packages/taquito/package.json').version"`" >> $GITHUB_ENV
    - run: echo "BRANCH_NAME=`echo $GITHUB_REF | cut -d'/' -f 3`" >> $GITHUB_ENV
    - run: echo "TARGET_VERSION=${PACKAGE_VERSION}-${SHORT_SHA}--${BRANCH_NAME}" >> $GITHUB_ENV
    - run: npm --version
    - run: npm ci
    - run: npm run lerna -- bootstrap
    - run: find packages/ -mindepth 1 -maxdepth 2 -name README.md | xargs sed -i '1s/^/# WARNING This build is produced from a feature branch and could contain unreviewed changes from the public. Use with caution, do not use in production\n\n/'
    - run: npm run lerna -- version "${TARGET_VERSION}" --no-push --no-git-tag-version --yes
    - run: npm run version-stamp
    - run: npm run build
    - run: cd packages/taquito && npm run build:release && cd ../..
    - run: git config user.email "actions@github.com" && git config user.name "Github Actions"
    - run: git add . && git commit -m "committing changes to files to make lerna happy in next step, this is expected to never be pushed to remote"
    - run: echo ${VERDACCIO_TOKEN} >> ~/.npmrc
    - run: npm run lerna -- publish --dist-tag edge from-package --yes --registry https://npm.preview.tezostaquito.io/
    - if: github.event.pull_request != null
      run: |
          echo "COMMENT_BODY<<EOF"  >> $GITHUB_ENV
          echo "New packages have been deployed to the preview repository at https://npm.preview.tezostaquito.io/." >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "### Published packages:" >> $GITHUB_ENV
          echo "\`\`\`" >> $GITHUB_ENV
          find packages/ -mindepth 1 -maxdepth 2 -name package.json | xargs -I{} node -pe "require('./{}')['name']" | sed "s/^\(.*\)$/npm i \1@${TARGET_VERSION} --registry https:\/\/npm.preview.tezostaquito.io\//" >> $GITHUB_ENV
          echo "\`\`\`" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
    - if: github.event.pull_request != null
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.COMMENT_BODY
          })
