name: taquito.io pages deploy

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  CHATKIT_WORKFLOW_ID: ${{ secrets.CHATKIT_WORKFLOW_ID }}
jobs:
  publish-website:
    name: Publish taquito.io to Cloudflare Pages
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
      - run: npm ci
      - run: npm run build
      - name: Build TypeDoc API docs
        working-directory: .
        run: npm ci && npm run build-docs

      - name: Publish to Cloudflare Pages
        id: cloudflare_publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID}}
          projectName: taquito
          directory: website/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'


      # Notify the PR of the deploy preview
      - uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: taquito.io Preview
          message: 'A new deploy preview for taquito.io is available on Cloudflare Pages at ${{ steps.cloudflare_publish.outputs.URL }}'
