name: Netlify Preview Deploy

on:
  pull_request:
    branches: [master]

jobs:
## This job will deploy the netlify preview builds
  publish-website-preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: npm run lerna -- bootstrap
    - run: npm run lerna run build
      env:
        ALGOLIA_APPLICATION_ID: "example"
        ALGOLIA_SEARCH_API_KEY: "example"
        ALGOLIA_UPDATE_API_KEY: "example"
    - run: npm run build-docs
    - run: echo "short_sha=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
    - run: npm run netlify:preview
      env:
        CI: true
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    - uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'A new deploy preview is available on Netlify at https://${{ env.short_sha }}--tezostaquito.netlify.app'
          })
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: Taquito Notifications
        SLACK_ICON: https://imgur.com/1zlqzFu
        SLACK_TITLE: Message
        SLACK_MESSAGE: There is a new deployment preview available for Taquito at https://${{ env.short_sha }}--tezostaquito.netlify.app
