name: Shadownet Integration Tests

on:
  push:
    branches:
      - '**shadownet**'

jobs:
  integration-tests-shadownet:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/Hydrogen
      - run: npm ci
      - run: npm run build
      - if: always()
        id: integration-tests-shadownet
        run: npm -w integration-tests run test:shadownet -- --maxWorkers=4